"""Adds unique constraint to user email

Revision ID: 00590d8bb336
Revises: fc9d7e83a03a
Create Date: 2021-05-02 20:54:05.727979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00590d8bb336'
down_revision = 'fc9d7e83a03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_email', type_='unique')

    # ### end Alembic commands ###
