"""Add Seer to project

Revision ID: 00dace2d42c6
Revises: aceed6d7db69
Create Date: 2021-07-05 18:26:32.150137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dace2d42c6'
down_revision = 'aceed6d7db69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['seer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('seer_id')
        batch_op.drop_column('has_seer')

    # ### end Alembic commands ###
