"""Project stages

Revision ID: 0621a5877cd7
Revises: d8682cade7c3
Create Date: 2021-06-25 20:44:36.249535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0621a5877cd7'
down_revision = 'd8682cade7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('project_project_stage_id_fkey', type_='foreignkey')
        batch_op.drop_column('project_stage_id')

    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_stage_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('project_project_stage_id_fkey', 'project_stage', ['project_stage_id'], ['id'])

    # ### end Alembic commands ###
