"""New User info

Revision ID: 13a6548472e0
Revises: ec0ab2755014
Create Date: 2021-06-14 18:25:12.870885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a6548472e0'
down_revision = 'ec0ab2755014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('creation_date_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_seeder', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_seer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_sponsor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('username')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_sponsor')
        batch_op.drop_column('is_seer')
        batch_op.drop_column('is_seeder')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('first_name')
        batch_op.drop_column('description')
        batch_op.drop_column('creation_date_time')
        batch_op.drop_column('avatar')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
