"""Add URI to projects

Revision ID: 15cc416a9b05
Revises: 2dea383105db
Create Date: 2021-07-03 17:23:06.403962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cc416a9b05'
down_revision = '2dea383105db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('uri_image')

    # ### end Alembic commands ###
