"""Category Association User

Revision ID: 24f1df018932
Revises: 84f4461c7cfa
Create Date: 2021-06-25 12:04:32.032909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f1df018932'
down_revision = '84f4461c7cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_association',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.name'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('category_association')
    # ### end Alembic commands ###
