"""Hashtag Association

Revision ID: 27097915a706
Revises: 7c2ec82f8a53
Create Date: 2021-06-22 16:58:01.767904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27097915a706'
down_revision = '7c2ec82f8a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag_project',
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('hashtag_id', 'project_id')
    )
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_hashtag', ['hashtag'])
        batch_op.drop_constraint('hashtag_id_project_fkey', type_='foreignkey')
        batch_op.drop_column('id_project')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_seer', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_seeder', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_sponsor', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creation_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_project', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('hashtag_id_project_fkey', 'project', ['id_project'], ['id'])
        batch_op.drop_constraint('unique_hashtag', type_='unique')

    op.drop_table('hashtag_project')
    # ### end Alembic commands ###
