"""Projects has many hashtags

Revision ID: 2dea383105db
Revises: 0621a5877cd7
Create Date: 2021-07-01 16:26:45.154804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dea383105db'
down_revision = '0621a5877cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_hashtag',
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag'], ['hashtag.hashtag'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('hashtag', 'project_id')
    )
    op.drop_table('hashtag_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag_association',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='hashtag_association_project_id_fkey')
    )
    op.drop_table('association_hashtag')
    # ### end Alembic commands ###
