"""Initial status schema

Revision ID: 3cee36d8a961
Revises:
Create Date: 2021-05-06 23:04:52.782688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cee36d8a961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('IN_PROGRESS', 'ALMOST_DONE', 'COMPLETE', name='state'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('goal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='unique_user_email')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('goal', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('SPORTS', 'ART', 'MUSIC', 'OTHERS', name='category'), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtag')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('project_state')
    # ### end Alembic commands ###
