"""Hashtag Association Project

Revision ID: 52d4d545351c
Revises: 84f4461c7cfa
Create Date: 2021-06-22 17:26:26.389593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d4d545351c'
down_revision = '84f4461c7cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag_association',
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag'], ['hashtag.hashtag'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )
    op.drop_table('hashtag_project')
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.alter_column('hashtag',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('hashtag',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('hashtag_project',
    sa.Column('hashtag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], name='hashtag_project_hashtag_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='hashtag_project_project_id_fkey'),
    sa.PrimaryKeyConstraint('hashtag_id', 'project_id', name='hashtag_project_pkey')
    )
    op.drop_table('hashtag_association')
    # ### end Alembic commands ###
