"""Change wallet ID to String

Revision ID: 5a4d2b1515c6
Revises: e591bdcc4de6
Create Date: 2021-06-27 20:29:20.177717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4d2b1515c6'
down_revision = 'e591bdcc4de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_id', sa.String(), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('internal_id')

    # ### end Alembic commands ###
