"""Remove category type from project

Revision ID: 5bbe78b231dd
Revises: fb527e57cffd
Create Date: 2021-06-06 12:47:34.246587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bbe78b231dd'
down_revision = 'fb527e57cffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('category')

    sa.Enum(name='category').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', postgresql.ENUM('SPORTS', 'ART', 'MUSIC', 'OTHERS', name='category'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
