"""Add administration

Revision ID: 5fde10be0efa
Revises: 2dbf01e0ae5e
Create Date: 2021-05-23 11:25:14.732647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fde10be0efa'
down_revision = '2dbf01e0ae5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
