"""Add id to admin

Revision ID: 7a54a8e506ca
Revises: 75c81bcdce8d
Create Date: 2021-05-24 10:15:42.453693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a54a8e506ca'
down_revision = '75c81bcdce8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
