"""Remove isSeeder and isSponsor from user fields

Revision ID: 7c2ec82f8a53
Revises: fafd0937860d
Create Date: 2021-06-23 19:42:09.664551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2ec82f8a53'
down_revision = 'fafd0937860d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_sponsor')
        batch_op.drop_column('is_seeder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seeder', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_sponsor', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
