"""Add Seer to project

Revision ID: aceed6d7db69
Revises: e6be07ed5a99
Create Date: 2021-07-05 18:25:49.292372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aceed6d7db69'
down_revision = 'e6be07ed5a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seer_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['seer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('seer_id')
        batch_op.drop_column('has_seer')

    # ### end Alembic commands ###
