"""Initial Schema

Revision ID: b679019a9f35
Revises:
Create Date: 2021-05-25 16:10:26.991027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b679019a9f35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('project_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('IN_PROGRESS', 'ALMOST_DONE', 'COMPLETE', name='stage'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('goal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='unique_user_email')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('current_state', sa.Enum('CREATED', 'ACTIVE', 'BLOCKED', 'CANCELLED', 'COMPLETE', 'EXPIRED', name='state'), nullable=True),
    sa.Column('goal', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('SPORTS', 'ART', 'MUSIC', 'OTHERS', name='category'), nullable=True),
    sa.Column('project_stage_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_stage_id'], ['project_stage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtag')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('project_stage')
    op.drop_table('admin')
    # ### end Alembic commands ###
