"""User info

Revision ID: ba092d7b6130
Revises: ec0ab2755014
Create Date: 2021-06-14 18:07:38.681867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba092d7b6130'
down_revision = 'ec0ab2755014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtag_project')
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_project', sa.Integer(), nullable=True))
        batch_op.drop_constraint('unique_hashtag', type_='unique')
        batch_op.create_foreign_key(None, 'project', ['id_project'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('unique_hashtag', ['hashtag'])
        batch_op.drop_column('id_project')

    op.create_table('hashtag_project',
    sa.Column('hashtag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], name='hashtag_project_hashtag_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='hashtag_project_project_id_fkey'),
    sa.PrimaryKeyConstraint('hashtag_id', 'project_id', name='hashtag_project_pkey')
    )
    # ### end Alembic commands ###
