"""Hashtag association to class

Revision ID: c15fb0ef6098
Revises: 0621a5877cd7
Create Date: 2021-06-30 15:42:13.970423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15fb0ef6098'
down_revision = '0621a5877cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_association',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.name'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.create_table('association_hashtag',
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag'], ['hashtag.hashtag'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('hashtag', 'project_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.alter_column('hashtag',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint('unique_hashtag', ['hashtag'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_project')
        batch_op.drop_column('id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_name'], ['name'])
        batch_op.drop_column('project_stage_id')

    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.drop_column('stage')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('creation_date_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_seer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('username')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_seer')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('first_name')
        batch_op.drop_column('description')
        batch_op.drop_column('creation_date_time')
        batch_op.drop_column('address')

    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sa.VARCHAR(length=11), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('title')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_stage_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project_stage', ['project_stage_id'], ['id'])
        batch_op.drop_column('category_name')

    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('id_project', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'project', ['id_project'], ['id'])
        batch_op.drop_constraint('unique_hashtag', type_='unique')
        batch_op.alter_column('hashtag',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('favorites')
    op.drop_table('association_hashtag')
    op.drop_table('category_association')
    # ### end Alembic commands ###
