"""Add user new information

Revision ID: c4fa1e8f4049
Revises: fb527e57cffd
Create Date: 2021-06-06 11:35:07.429933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fa1e8f4049'
down_revision = 'fb527e57cffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
