"""Index in stages

Revision ID: c76968c1c20b
Revises: 1e0c139a6289
Create Date: 2021-07-16 17:52:57.725653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76968c1c20b'
down_revision = '1e0c139a6289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stage_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.drop_column('stage_index')
        batch_op.drop_column('creation_date')

    # ### end Alembic commands ###
