"""Add state

Revision ID: c822d6f63e0e
Revises: 3cee36d8a961
Create Date: 2021-05-06 23:07:02.813043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c822d6f63e0e'
down_revision = '3cee36d8a961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'project_state', ['project_state_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_state_id')

    # ### end Alembic commands ###
