"""Fund release at

Revision ID: d3b9d36501aa
Revises: 323d4a93373b
Create Date: 2021-07-25 11:28:23.887873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b9d36501aa'
down_revision = '323d4a93373b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funds_released_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.drop_column('funds_released_at')

    # ### end Alembic commands ###
