"""Add proper stage and state to project

Revision ID: d8682cade7c3
Revises: 299e2bc265af
Create Date: 2021-06-25 19:36:16.509174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8682cade7c3'
down_revision = '299e2bc265af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.drop_column('stage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', postgresql.ENUM('IN_PROGRESS', 'ALMOST_DONE', 'COMPLETE', name='stage'), autoincrement=False, nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
