"""add todo model

Revision ID: d93b730c96f1
Revises:
Create Date: 2021-04-21 20:00:04.010007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93b730c96f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_simple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_simple')
    # ### end Alembic commands ###
