"""Adds unique constraint to user email

Revision ID: eb8f3789ef9f
Revises: fc9d7e83a03a
Create Date: 2021-05-02 10:26:34.252260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8f3789ef9f'
down_revision = 'fc9d7e83a03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
